### ISSUE TITLE
Nuke 13 walrus operator issue

### ISSUE THREAD

**Issue by Ripax** [ToqueIO/panelHacker#1]
Nuke 13 not supported walrus operator.

**Comment by ToqueIO** [comment]
Hey @Ripax my apologies for not seeing this sooner as I was away on vacation visiting with family.

I had not thought about that at all and will have a look into the pull request you made and see about making a compatible branch for nuke 13

Cheers!
Josh

**Comment by ToqueIO** [comment]
Your request has been merged out into a new branch called nuke13 so that the primary branch can maintain the walrus operator.  I will create a new release as well

Thanks again for flagging this

Cheers!

**Comment by Ripax** [comment]
Thanks for your update
